### ISSUE TITLE
updates to Stock Synthesis entry in nmfs-fish-tools.github.io

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-fish-tools/nmfs-fish-tools.github.io#6]
A few simple changes could be made to the Stock Synthesis entry: https://github.com/nmfs-fish-tools/nmfs-fish-tools.github.io/blob/master/index.html#L1090-L1126, including
- [x] change the header from "SS" to "SS3" reflecting change in other places suggested by @Rick-Methot-NOAA (see https://github.com/nmfs-stock-synthesis/doc/issues/77)
- [x] add release version badge (e.g. https://img.shields.io/github/v/release/nmfs-stock-synthesis/stock-synthesis)

Other changes could come later for additional Stock Synthesis-related repos, including 
- [x] add release version badge for SSMSE as well (cc @k-doering-NOAA)
- [ ] adding ss3sim to the set (cc @kellijohnson-NOAA)

**Comment by k-doering-NOAA** [comment]
thanks @iantaylor-NOAA ! Tagging @ChristineStawitz-NOAA and @Bai-Li-NOAA  just to make sure this request is visible - but all this is not a rush and can wait.

**Comment by Rick-Methot-NOAA** [comment]
Also, let's put SSS (Chantel&Jason) and SSI (Neal) in the pipeline. Even less of a rush.

**Comment by k-doering-NOAA** [comment]
added to https://github.com/noaa-fisheries-integrated-toolbox/toolbox_web_templating/issues/2
